export const ADD_TODO = 'ADD_TODO';

export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_COMPLETED = 'SHOW_COMPLETED';
export const SHOW_INCOMPLETE = 'SHOW_INCOMPLETE';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';